export const TYPES = {
  AUTH: 'AUTH',
  ALERT: 'ALERT',
  STATUS: 'STATUS',
  MODAL: 'MODAL'
}

export const PROFILE_TYPES = {
  LOADING: 'LOADING_PROFILE',
  GET_USER: 'GET_USER_PROFILE',
  FOLLOW: 'FOLLOW',
  UNFOLLOW: 'UNFOLLOW',
  GET_ID: 'GET_ID_PROFILE',
  GET_POSTS: 'GET_PROFILE_POSTS'
}

export const POST_TYPES = {
  CREATE_POST: 'CREATE_POST',
  LOADING_POST: 'LOADING_POST',
  GET_POSTS: 'GET_POSTS',
  GET_POST: 'GET_POST',
  UPDATE_POST: 'UPDATE_POST'
}
